version: 0.1.1
env:
  - BUILD_MACHINE: "Dynamo_Win_003"
  - SLACK_QUANTUM_BUILD_CHANNEL : "#dynamo-jenkinsbuild"
  - SLACK_QUANTUM_BUILD_CREDENTIAL_ID : "slack-notify-token"
  - MAIL_QUANTUM_BUILD_RECIPIENT : "dynamo.plaid.dev@autodesk.com"
  - TEST_REPORT_FORMAT : "nunit"
  
check_changelog_updated_on_pr: false
pipeline_os: "Windows"
force_slack_notification : true

job_parameters:
    -
      type: "choice"
      name: "ENVIRONMENT_LANGUAGE"
      choices: 
        - "en"
        - "de"
        - "ja"
        - "zh-tw"
      description: ""

build:
  before_scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\PreBuildScript.ps1"
  scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\BuildScript.ps1"
    - "gswin64c.exe -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -dColorImageResolution=125dpi -sOutputFile=.\\%ENVIRONMENT_LANGUAGE%\\_book\\Appendix\\DynamoPrimer-Print.pdf  .\\%ENVIRONMENT_LANGUAGE%\\_book\\Appendix\\DynamoPrimer.pdf"
  after_scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\PostBuildScript.ps1"
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\DeployScript.ps1"
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\PostDeployScript.ps1"

deployment:
-
  type: customized
  scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\DeployScript.ps1"
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\PostDeployScript.ps1"
