version: 0.1.1
env:
  - JENKINS_NODE_WIN: "Dynamo_Win_Perf"
  - SLACK_QUANTUM_BUILD_CHANNEL : "#dynamo-jenkinsbuild"
  - SLACK_QUANTUM_BUILD_CREDENTIAL_ID : "slack-notify-token"
  - MAIL_QUANTUM_BUILD_RECIPIENT : "dynamo.dev@autodesk.com"
  - DOCKER_IMAGE_VERSION : "1.0.5"
  - PDFCOMPRESS_COLORIMAGERESOLUTION : "125dpi"
  - PDFCOMPRESS_PDFSETTINGS : "screen"
  - PDFCOMPRESS_DEVICE : "pdfwrite"
  - BUCKETNAME : "primer.dynamobim.org"
  - DISTRIBUTIONID : "E1L4E92B2OBQIF"
  - DOCKER_WORKSPACE : "C:\\WorkspacePrimer"
  - LIBRARIES_FOLDER : "WSThirdPartyLibraries"
  - DOCKER_CONTAINER : "build-primer"
  - COMMON_RESOURCES_DIR : "cicdresources"
  - URL_REPO_TOOLS : "https://github.com/DynamoDS/DynamoPrimer"
  - BRANCH_TOOLS : "cicdresources"
  - HARMONY_REPO : "DynamoDS/DynamoPrimer"

timeout: 420
check_changelog_updated_on_pr: false
pipeline_os: "Windows"
force_slack_notification : true

job_parameters:
    -
      type: "extendedChoice"
      name: "ENVIRONMENT_LANGUAGE"
      value: "en,de,ja,zh-tw,cs,es,fr,it,ko,pl,pt-br,ru,zh-cn"
      defaultValue: "en,de,ja,zh-tw,cs,es,fr,it,ko,pl,pt-br,ru,zh-cn"
      delimiter: ","
      description: ""

build:
  -
    scripts:
      - "pwsh.exe -ExecutionPolicy ByPass -File .\\utils\\DownloadCICDResources.ps1"
      - "pwsh.exe -ExecutionPolicy ByPass -File .\\%COMMON_RESOURCES_DIR%\\scripts\\SetupHost.ps1"
      - "pwsh.exe -ExecutionPolicy ByPass -File .\\%COMMON_RESOURCES_DIR%\\scripts\\PreBuildScript.ps1"
      - "pwsh.exe -ExecutionPolicy ByPass -File .\\%COMMON_RESOURCES_DIR%\\scripts\\BuildScript.ps1"
      - "pwsh.exe -ExecutionPolicy ByPass -File .\\%COMMON_RESOURCES_DIR%\\scripts\\CopyLibrariesToHostScript.ps1"
      - "pwsh.exe -ExecutionPolicy ByPass -File .\\%COMMON_RESOURCES_DIR%\\scripts\\PostBuildScript.ps1"
      - "pwsh.exe -ExecutionPolicy ByPass -File .\\%COMMON_RESOURCES_DIR%\\scripts\\DeployScript.ps1"
      - "pwsh.exe -ExecutionPolicy ByPass -File .\\%COMMON_RESOURCES_DIR%\\scripts\\PostDeployScript.ps1"
  
soc2:
  run_on_any_branch : true
  harmony:    
    hidden_email_list: dynamo_ws_access
    repository: env.HARMONY_REPO
    third_party_lib_paths:
      - "%LIBRARIES_FOLDER%\\gs9.50"
      - "%LIBRARIES_FOLDER%\\Modules"
      - "%LIBRARIES_FOLDER%\\gitbook-cli"
      - "%LIBRARIES_FOLDER%\\Calibre2"
      - "%LIBRARIES_FOLDER%\\Vault"
      
schedule:
  cron_schedule: "once_a_month"
